#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

source ../config.sh

docker pull $UCD_LIB_DOCKER_ORG/$UCD_CORE_SERVER_NAME:$UCD_CORE_SERVER_VERSION

docker build \
  --cache-from $UCD_LIB_DOCKER_ORG/$UCD_CORE_SERVER_NAME:$UCD_CORE_SERVER_VERSION \
  --build-arg APP_VERSION=${APP_VERSION} \
  --build-arg UCD_CORE_SERVER_VERSION=${UCD_CORE_SERVER_VERSION} \
  --build-arg FCREPO_VERSION=${FCREPO_VERSION} \
  --build-arg PG_VERSION=${PG_VERSION} \
  --build-arg ELASTIC_SEARCH_VERSION=${ELASTIC_SEARCH_VERSION} \
  --build-arg TRUSTED_PROXY_VERSION=${TRUSTED_PROXY_VERSION} \
  --build-arg UCD_LIB_CLIENT_VERSION=${UCD_LIB_CLIENT_VERSION} \
  --build-arg ESSYNC_VERSION=${ESSYNC_VERSION} \
  --build-arg CAS_VERSION=${CAS_VERSION} \
  --build-arg LORIS_VERSION=${LORIS_VERSION} \
  --build-arg TESSERACT_VERSION=${LORIS_VERSION} \
  -t $UCD_LIB_DOCKER_ORG/$FIN_UCD_SERVER_NAME:$APP_VERSION \
  .