version: '3'

###
# Fin Server from deployed DockerHub container images
###
services:

  ###
  # Font End NodeJS Application Server
  ###
  server:
    image: ucdlib/fin-ucd-lib-server-impl:{{APP_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
      - ../repositories/fin-server/server/controllers:/app/controllers
      - ../repositories/fin-server/server/lib:/app/lib
      - ../repositories/fin-server/server/index.js:/app/index.js
      - ../repositories/fin-server/server/assets:/app/assets
      - ../repositories/fin-server/server/models:/app/models
      - ../repositories/fin-server/node-utils/lib:/fin-node-utils/lib
      - ../repositories/fin-server/node-utils/config.js:/fin-node-utils/config.js
      - ../repositories/fin-server/node-utils/index.js:/fin-node-utils/index.js
      - ../repositories/fin-ucd-lib-server/server/transforms:/etc/fin/transforms
      - ../repositories/fin-ucd-lib-server/server/core-services.js:/etc/fin/core-services.js
      - ../ucd-lib-server-impl/app-services.js:/etc/fin/app-services.js
    ports:
      - ${HOST_PORT:-3000}:3001
    env_file:
      - .env
    depends_on:
      - fcrepo
      - redis
      - elasticsearch
    # command: bash -c 'tail -f /dev/null'

  ###
  # Fedora Repository
  ###
  fcrepo:
    image: ucdlib/fin-fcrepo:{{CORE_SERVER_REPO_TAG}}
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
    env_file:
      - .env

  ###
  # Fedora Postgres Service
  ###
  postgres:
    image: ucdlib/fin-postgres:{{CORE_SERVER_REPO_TAG}}
    volumes:
      - pg-data:/var/lib/postgresql/data

  ###
  # Trusted Proxy for Services
  ###
  trustedproxy:
    image: ucdlib/fin-trusted-proxy:{{CORE_SERVER_REPO_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
      - ../repositories/fin-server/trusted-proxy/index.js:/service/index.js
      - ../repositories/fin-server/node-utils/lib:/fin-node-utils/lib
      - ../repositories/fin-server/node-utils/config.js:/fin-node-utils/config.js
      - ../repositories/fin-server/node-utils/index.js:/fin-node-utils/index.js
    env_file:
      - .env
    depends_on:
      - fcrepo
    # command: bash -c 'tail -f /dev/null'

  ###
  # Session, admin store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo

  ###
  # UC DAMS Client UI
  ###
  ucd-lib-client:
    image: ucdlib/fin-ucd-lib-client:{{UCD_LIB_SERVER_REPO_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
      - ../repositories/fin-ucd-lib-server/services/ucd-lib-client/index.js:/service/index.js
      - ../repositories/fin-ucd-lib-server/services/ucd-lib-client/config.js:/service/config.js
      - ../repositories/fin-ucd-lib-server/services/ucd-lib-client/client:/service/client
      - ../repositories/fin-ucd-lib-server/services/ucd-lib-client/controllers:/service/controllers
      - ../repositories/fin-ucd-lib-server/services/ucd-lib-client/lib:/service/lib
      - ../repositories/fin-ucd-lib-server/services/ucd-lib-client/models:/service/models
      - ../repositories/fin-server/node-utils/lib:/fin-node-utils/lib
      - ../repositories/fin-server/node-utils/config.js:/fin-node-utils/config.js
      - ../repositories/fin-server/node-utils/index.js:/fin-node-utils/index.js
    env_file:
      - .env
    depends_on:
      - elasticsearch
    # command: bash -c 'tail -f /dev/null'

  ###
  # ES Indexer
  ###
  essync:
    image: ucdlib/fin-essync:{{UCD_LIB_SERVER_REPO_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
      - ../repositories/fin-ucd-lib-server/services/essync/lib:/service/lib
      - ../repositories/fin-ucd-lib-server/services/essync/schemas:/service/schemas
      - ../repositories/fin-ucd-lib-server/services/essync/index.js:/service/index.js
      - ../repositories/fin-ucd-lib-server/services/essync/reindex.js:/service/reindex.js
      - ../repositories/fin-server/node-utils/lib:/fin-node-utils/lib
      - ../repositories/fin-server/node-utils/config.js:/fin-node-utils/config.js
      - ../repositories/fin-server/node-utils/index.js:/fin-node-utils/index.js
    env_file:
      - .env
    depends_on:
      - server
    # command: bash -c 'tail -f /dev/null'

  ###
  # Search
  ###
  elasticsearch:
    image: ucdlib/fin-elasticsearch:{{UCD_LIB_SERVER_REPO_TAG}}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    depends_on:
      - fcrepo
    # command: bash -c 'tail -f /dev/null'

  ###
  # IIIF Service
  ###
  loris:
    image: ucdlib/fin-loris:{{LORIS_SERVICE_REPO_TAG}}
    depends_on:
      - fcrepo
    env_file:
      - .env
    volumes:
      - loris-cache:/var/cache/loris
      - ../repositories/fin-service-loris/loris2.conf:/opt/loris/etc/loris2.conf
      - ../repositories/fin-service-loris/start.py:/opt/loris/loris/start.py

  ###
  # Tesseract OCR Services
  ###
  tesseract:
    image: ucdlib/fin-tesseract:{{TESSERACT_SERVICE_REPO_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
      - ../repositories/fin-service-tesseract/index.js:/service/index.js
      - ../repositories/fin-server/node-utils/lib:/fin-node-utils/lib
      - ../repositories/fin-server/node-utils/config.js:/fin-node-utils/config.js
      - ../repositories/fin-server/node-utils/index.js:/fin-node-utils/index.js
    env_file:
      - .env
    depends_on:
      - server
    # command: bash -c 'tail -f /dev/null'

  ###
  # CAS AuthenticationService
  ###
  cas:
    image: ucdlib/fin-cas:{{CAS_SERVICE_REPO_TAG}}
    volumes:
      - ${GCLOUD_SERVICE_ACCOUNT_MOUNT:-service-account}:/etc/fin/webapp-service-account.json
      - ../repositories/fin-service-cas/controller.js:/service/controller.js
      - ../repositories/fin-service-cas/index.js:/service/index.js
      - ../repositories/fin-server/node-utils/lib:/fin-node-utils/lib
      - ../repositories/fin-server/node-utils/config.js:/fin-node-utils/config.js
      - ../repositories/fin-server/node-utils/index.js:/fin-node-utils/index.js
    env_file:
      - .env
    depends_on:
      - server
    # command: bash -c 'tail -f /dev/null'


###
# Docker data volumes
###
volumes:
  fedora-data:
    driver: local
  pg-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  loris-cache:
    driver: local
  service-account:
    driver: local