steps:

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['rsync', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}', '/config']
  #   volumes:
  #   - name: 'config'
  #     path: '/config'

  # - name: 'gcr.io/$PROJECT_ID/ci-buildnum'
  #   args: ['/config/buildnum', '/config/.buildenv']
  #   volumes:
  #   - name: 'config'
  #     path: '/config'

  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', '/config/buildnum', 'gs://${_CONFIG_BUCKET}/${_CONFIG_PROJECT}/buildnum']
  #   volumes:
  #   - name: 'config'
  #     path: '/config'

  # - name: gcr.io/cloud-builders/gcloud
  #   entrypoint: 'bash'
  #   args: [ '-c', 'gcloud secrets versions access latest --secret=libosdev-dockerhub-secret > pass.txt' ]
  #   # this is a hack to get the BRANCH_NAME and SHORT_SHA in the build metadata even when
  #   # submitted from via ./gcloud/push.sh.  All --substitutions variables have to exist in the
  #   # yaml file.  Even when you are substiting special variables like BRANCH_NAME and SHORT_SHA (lame).
  #   env: 
  #     - 'REPO_NAME=$REPO_NAME'
  #     - 'BRANCH_NAME=$BRANCH_NAME'
  #     - 'SHORT_SHA=$SHORT_SHA'
  #     - 'TAG_NAME=$TAG_NAME'
  
  # - name: "gcr.io/cloud-builders/docker"
  #   entrypoint: "bash"
  #   args: ["-c", "docker login --username=libosdev --password-stdin < pass.txt"]

  # - name: gcr.io/cloud-builders/git
  #   entrypoint: "bash"
  #   args: ["-c", "./cmds/clone.sh"]

  # - name: gcr.io/cloud-builders/docker
  #   entrypoint: "bash"
  #   args: ["-c", "./cmds/pull.sh"]

  # - name: gcr.io/cloud-builders/docker
  #   entrypoint: "bash"
  #   args: ["-c", "./cmds/build.sh"]
  #   env: 
  #     - 'GCLOUD_BUILD=true'
  #   volumes:
  #   - name: 'config'
  #     path: '/config'

  # - name: gcr.io/cloud-builders/docker
  #   entrypoint: "bash"
  #   args: ["-c", "./cmds/push.sh"]
  #   volumes:
  #   - name: 'config'
  #     path: '/config'

  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SANDBOX_SSH_KEY', 'SANDBOX_KNOWN_HOSTS']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "$$SANDBOX_SSH_KEY" >> /root/.ssh/gcb
      chmod 400 /root/.ssh/gcb
      echo "$$SANDBOX_KNOWN_HOSTS" >> /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: "bash"
    args: ["-c", "./gcloud/deploy.sh"]
    volumes:
    - name: 'ssh'
      path: /root/.ssh
    env: 
      - 'REPO_NAME=$REPO_NAME'
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'
      - 'PROJECT_BUILD_BUCKET=$_CONFIG_BUCKET'
      - 'PROJECT_ID=$_CONFIG_PROJECT'
  

substitutions:
  _CONFIG_BUCKET: ci-build-config
  _CONFIG_PROJECT: dams

availableSecrets:
  secretManager:
  - versionName: projects/digital-ucdavis-edu/secrets/sandbox-vm-ssh/versions/latest
    env: 'SANDBOX_SSH_KEY'
  - versionName: projects/digital-ucdavis-edu/secrets/sandbox-vm-known-hosts/versions/latest
    env: 'SANDBOX_KNOWN_HOSTS'


timeout: 1800s