#! /bin/bash

set -e
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $ROOT_DIR
source ../config.sh

docker push $UCD_LIB_DOCKER_ORG/$FCREPO_IMAGE_NAME:$CORE_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$POSTGRES_IMAGE_NAME:$CORE_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$NODE_UTILS_IMAGE_NAME:$CORE_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$SERVER_IMAGE_NAME:$CORE_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$TRUSTED_PROXY_IMAGE_NAME:$CORE_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$ELASTIC_SEARCH_IMAGE_NAME:$UCD_LIB_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$UCD_LIB_SERVER_IMAGE_NAME:$UCD_LIB_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$ESSYNC_IMAGE_NAME:$UCD_LIB_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$UCD_LIB_CLIENT_IMAGE_NAME:$UCD_LIB_SERVER_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$LORIS_IMAGE_NAME:$LORIS_SERVICE_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$TESSERACT_IMAGE_NAME:$TESSERACT_SERVICE_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$CAS_IMAGE_NAME:$CAS_SERVICE_REPO_TAG
docker push $UCD_LIB_DOCKER_ORG/$UCD_LIB_SERVER_IMPL:$APP_VERSION